//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortgageCalculator.Dto.MortgageData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mortgage
    {
        public int MortgageId { get; set; }
        public string Name { get; set; }
        public int MortgageTypeId { get; set; }
        public int InterestRepaymentId { get; set; }
        public System.DateTime EffectiveStartDate { get; set; }
        public System.DateTime EffectiveEndDate { get; set; }
        public int TermsInMonths { get; set; }
        public decimal CancellationFee { get; set; }
        public decimal EstablishmentFee { get; set; }
        public System.Guid SchemaIdentifier { get; set; }
    
        public virtual InterestRepayment InterestRepayment { get; set; }
        public virtual MortgageType MortgageType { get; set; }
    }
}
