//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortgageCalculator.Dto.MortgageData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MortgageType
    {
        public MortgageType()
        {
            this.Mortgages = new HashSet<Mortgage>();
        }
    
        public int MortgageTypeId { get; set; }
        public string MortgageTypeName { get; set; }
    
        public virtual ICollection<Mortgage> Mortgages { get; set; }
    }
}
