//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortgageCalculator.Dto.MortgageData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MortgageDataContext : DbContext
    {
        public MortgageDataContext()
            : base("name=MortgageDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<InterestRepayment> InterestRepayments { get; set; }
        public DbSet<Mortgage> Mortgages { get; set; }
        public DbSet<MortgageType> MortgageTypes { get; set; }
    }
}
